package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func InitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init [moniker]",
		Short: "Initialize NEXUS node",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			moniker := args[0]
			home, _ := cmd.Flags().GetString("home")
			if home == "" {
				home = defaultHome
			}
			home = os.ExpandEnv(home)

			// Create directories
			configDir := filepath.Join(home, "config")
			dataDir := filepath.Join(home, "data")
			os.MkdirAll(configDir, 0755)
			os.MkdirAll(dataDir, 0755)

			// Create genesis.json
			genesis := map[string]interface{}{
				"genesis_time":   "2024-01-01T00:00:00Z",
				"chain_id":       "nexus-1",
				"initial_height": "1",
				"consensus_params": map[string]interface{}{
					"block": map[string]interface{}{
						"max_bytes": "22020096",
						"max_gas":   "-1",
					},
				},
				"app_state": map[string]interface{}{
					"bank": map[string]interface{}{
						"balances": []interface{}{},
					},
					"dualapproval": map[string]interface{}{
						"checkpoints": []interface{}{},
						"miners":      []interface{}{},
						"params": map[string]interface{}{
							"checkpoint_interval":    200,
							"min_checkpoint_signers": 5,
							"checkpoint_threshold":   67,
						},
					},
				},
			}

			genesisBytes, _ := json.MarshalIndent(genesis, "", "  ")
			genesisPath := filepath.Join(configDir, "genesis.json")
			os.WriteFile(genesisPath, genesisBytes, 0644)

			// Create config.toml
			configToml := fmt.Sprintf(`# NEXUS Node Configuration
# Generated by nexusd init

[node]
moniker = "%s"
chain_id = "nexus-1"

[rpc]
listen_addr = "tcp://127.0.0.1:26657"
cors_allowed_origins = ["*"]

[p2p]
listen_addr = "tcp://0.0.0.0:26656"
seeds = ""
persistent_peers = ""

[consensus]
# Block time target
timeout_commit = "3s"

[dualapproval]
# Checkpoint every N blocks
checkpoint_interval = 200

# Minimum miners required for checkpoint
min_signers = 5

# Approval threshold percentage
threshold = 67

# Enable mining on this node
enable_mining = false
miner_address = ""

[mining]
# Path to Vina binary
vina_path = "./vina_1.2.5_linux_x86_64"

# Number of parallel docking jobs
num_workers = 4

# IPFS gateway for ligand downloads
ipfs_gateway = "https://ipfs.io/ipfs/"
`, moniker)

			configPath := filepath.Join(configDir, "config.toml")
			os.WriteFile(configPath, []byte(configToml), 0644)

			// Create node key (placeholder)
			nodeKey := map[string]string{
				"priv_key": "placeholder_generate_real_key",
			}
			nodeKeyBytes, _ := json.MarshalIndent(nodeKey, "", "  ")
			os.WriteFile(filepath.Join(configDir, "node_key.json"), nodeKeyBytes, 0644)

			fmt.Println("Initialized NEXUS node")
			fmt.Println("======================")
			fmt.Printf("Home:     %s\n", home)
			fmt.Printf("Moniker:  %s\n", moniker)
			fmt.Println("Chain ID: nexus-1")
			fmt.Println("")
			fmt.Println("Files created:")
			fmt.Printf("  %s\n", filepath.Join(configDir, "genesis.json"))
			fmt.Printf("  %s\n", filepath.Join(configDir, "config.toml"))
			fmt.Printf("  %s\n", filepath.Join(configDir, "node_key.json"))
			fmt.Println("")
			fmt.Println("Next steps:")
			fmt.Println("  1. Edit config.toml to configure your node")
			fmt.Println("  2. Run: nexusd start")
			fmt.Println("  3. Register as miner: nexusd miner register [address]")

			return nil
		},
	}
	return cmd
}
